export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_ACTION_DONE = "LOGIN_ACTION_DONE";
export const LOGIN_ACTION_ERROR = "LOGIN_ACTION_ERROR";

export const LOGIN_RESET_CONFIG_ACTION = "LOGIN_RESET_CONFIG_ACTION";
